src/main.cpp
The data field is required to properly locate QtWebEngine resources.
=> Add Data field to the qt.conf file

lib/CMakeLists.txt, src/main.cpp, src/util.h
Search for `.qm` files outside the `usr/translations` dir and copy them into it. 
Provides a solution for #16 depends on https://github.com/linuxdeploy/linuxdeploy/pull/40
=> Copy application translation files (.qm) into the usr/translations dir.

.travis.yml, src/main.cpp, travis/test.sh
The Wayland support required that we binaries were built using ubuntu xenial which makes the plug-in unusable in older distributions also it has other side effects (see #22) that can be better described by @TheAssassin.
This will revert changes related to the Wayland plugin support.
=> Undo wayland plugging support

src/main.cpp
The `bf::directory_iterator` might throw when the directory does not exist, and the styles plugin seems to have been removed in Qt 5.12.3 (well, 5.12 probably).
=> Make sure the experimental platform themes deployment does not throw

src/main.cpp
This fixes the failed builds when QGtk 2 Theme and/or Style are not installed or found.
But beware, the app developer must take care of ensuring that the QGtk 2 Theme and/or Style is built and properly installed on the build environment.
@TheAssassin builds were failing because once a file is set for deployment they must exists or the build fails.
=> Make QGtk 2 Theme and Style deployment optional

src/util.h
According to: https://docs.python.org/2/library/subprocess.html#subprocess.Popen.wait
>> `Popen::wait` will deadlock when using stdout=PIPE and/or stderr=PIPE and the child process generates enough output to a pipe such that it blocks waiting for the OS pipe buffer to accept more data. Use communicate() to avoid that.
Despite this documentation is not for cpp-subprocess, the later is inspired by the original Python module therefore similar errors can be expected.
This PR remove that ~possible and NOT proven~ possibility. Also makes the code more simple.
____
Update
I was blaming a bug on cpp-subprocess for being the cause of #37 but it happens that `Popen::wait` does hangs when used with pipes as the warning above states. So this also contributes to fixing #37
=> Fix check_command function

CMakeLists.txt, lib/CMakeLists.txt, tests/CMakeLists.txt
Right now you cannot build without building tests, this PR makes it possible to opt out by setting `cmake -DBUILD_TESTING=OFF path/to/repo`, which is I think the standard way cmake people do it (but i'm not an expert).
=> Make it possible to opt out of building tests

src/deployers/PluginsDeployerFactory.cpp
xcbgl integration was not deployed due to a copy-paste issue. Maybe I would have caught that had I reviewed the refactoring PR...
=> Fix copy-paste bug

src/deployers/PluginsDeployerFactory.cpp, src/deployers/PluginsDeployerFactory.h, src/main.cpp
Fixes the issue where only `PlatformPluginsDeployer` not `XcbglIntegrationPluginsDeployer` is deployed whenever `gui` is the only module found (#51).
=> Return multiple deployers per module

src/qml.cpp
Calculate the relative path to the imported QML file without resolving
symlinks. The path should be resolved lexically. This solves an issue
where a development QML plugin symlinks its files back to the
source.
=> Relative Path for QML files

src/deployers/PluginsDeployerFactory.cpp, src/deployers/PluginsDeployerFactory.h, src/main.cpp
They were added in Qt 6.2.
Closes #95.
=> Don't try to deploy TLS plugins for Qt 6.0 or 6.1

src/main.cpp, src/util.h
Qt 6.2 stores qmlimportscanner in the libexecs folder, linuxdeploy-plugin-qt uses which to determine the location so if the libexecs folder isn't added to PATH it may select qmlimportscanner from another Qt version or not find it at all.
=> Add libexecs to path

src/qt-modules.h
This PR follows on from https://github.com/linuxdeploy/linuxdeploy-plugin-qt/pull/113 by re-introducing all qt6modules that were previously left out during the 6.0-6.1 phase.
All Qt6 modules are (in theory) now available in >=6.2
https://www.qt.io/blog/qt-6.2-lts-released
Note: keeping the re-introduced modules in a separate block for now until we can confirm there are no wrinkles.
Also: As a guess, I changed `qtquick1` to `qtquick2` for the `declarative` module. I'm not sure about this yet though.
=> Re-introduce all qt6modules

README.md, ci/test.sh, src/deployers/PlatformPluginsDeployer.cpp
=> Allow installation of extra platform plugins

src/deployers/CMakeLists.txt, src/deployers/Multimedia5PluginsDeployer.cpp, src/deployers/Multimedia5PluginsDeployer.h, src/deployers/Multimedia6PluginsDeployer.cpp, src/deployers/Multimedia6PluginsDeployer.h, src/deployers/PluginsDeployerFactory.cpp
Adds support for deploying Qt 6 multimedia plugins. All of the multimedia plugin directories are now gated behind fs::exists checks to support both Qt 5 and Qt 6 configurations.
Fixes https://github.com/linuxdeploy/linuxdeploy-plugin-qt/issues/144
=> Support deploying Qt 6 multimedia plugins.

CMakeLists.txt
In main `CMakeLists.txt` file if `nlohmann_json` library is not found in system then is fetched from github repository by using `FetchContent_Declare` command which should be included from [FetchContent_Declare](https://cmake.org/cmake/help/latest/module/FetchContent.html) module. Without that include there is CMake error:
```
CMake Error at CMakeLists.txt:22 (FetchContent_Declare):
Unknown CMake command "FetchContent_Declare".
```
=> Adding missing include for CMake FetchContent_Declare command

src/qt-modules.h
Fixes ignored `export EXTRA_QT_PLUGINS="waylandcompositor"`
=> Add missing Qt5 Wayland modules

README.md, src/main.cpp
=> Rename EXTRA_QT_PLUGINS to EXTRA_QT_MODULES

src/deployers/WebEnginePluginsDeployer.cpp
This file was added in Qt6.
See https://doc.qt.io/qt-6/qtwebengine-deploying.html
=> Copy v8_context_snapshot.bin to resources when deploying Qt WebEngine.

src/deployers/BasicPluginsDeployer.cpp, src/deployers/TextToSpeechPluginsDeployer.cpp, src/deployment.h
This commit replicates a pattern from the TextToSpeechPluginsDeployer across a range of other deployer classes.
Essentially - it's extremely unlikely that composing an AppImage with debug symbols is what a user actually wants to do. I'm also not aware of a good story for connecting debug symbols to an AppImage at all.
As a result, let's make a sensible choice - and not package them. Trust that developers will use their underlying build system for Debug, and that release tracking will allow developers to tie an AppImage back to a source control revision.
Finally, note that this works around an interesting aarch64 bug - where the .debug files that are created are marked as x86_64 ELF binaries - even when you are _building on an aarch64 host_.
Fixes: #110, but not in the manner suggested by …
=> multiple deployers: Ignore .debug files

README.md
Mention that files in QML_SOURCES_PATHS are checked for imported modules, and that those modules will be included in AppDir.
It wasn't obvious to me how QML modules get included. Hopefully this helps the next guy.
=> Small QML_SOURCES_PATHS README addition

src/deployers/PlatformPluginsDeployer.cpp
When EXTRA_PLATFORM_PLUGINS has libqwayland-* we
should also deploy the shell and decoration
plugins.
=> Deploy Wayland Shell integration and decoration
